# Generated by Django 5.0.3 on 2024-03-24 10:10

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='firstname')),
                ('lastname', models.CharField(max_length=50, verbose_name='lastname')),
                ('birthdate', models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2010, 3, 28))], verbose_name='birthdate')),
                ('age', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(14)], verbose_name='age')),
                ('address', models.CharField(max_length=100, verbose_name='address')),
                ('sex', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=20, verbose_name='sex')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['firstname', 'lastname'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, verbose_name='product_name')),
                ('description', models.TextField()),
                ('start_date', models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2024, 3, 24))], verbose_name='start_date')),
                ('end_date', models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2024, 3, 24))], verbose_name='end_date')),
                ('clients', models.ManyToManyField(blank=True, to='web_bank.client', verbose_name='clients')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['product_name'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='products',
            field=models.ManyToManyField(blank=True, to='web_bank.product', verbose_name='product'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_name'], name='web_bank_pr_product_91223b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('firstname', 'lastname')},
        ),
    ]
