# Generated by Django 5.0.3 on 2024-03-25 17:41

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birthdate',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2010, 3, 29))], verbose_name='birthdate'),
        ),
        migrations.AlterField(
            model_name='product',
            name='end_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2024, 3, 25))], verbose_name='end_date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='start_date',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2024, 3, 25))], verbose_name='start_date'),
        ),
    ]
