# Generated by Django 5.0.3 on 2024-03-26 17:17

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_bank', '0002_alter_client_birthdate_alter_product_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birthdate',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2010, 3, 30))], verbose_name='birthdate'),
        ),
        migrations.AlterField(
            model_name='product',
            name='end_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2024, 3, 26))], verbose_name='end_date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='start_date',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2024, 3, 26))], verbose_name='start_date'),
        ),
    ]
