# Generated by Django 5.0.3 on 2024-03-26 17:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_bank', '0003_alter_client_birthdate_alter_product_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cred_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='type'),
            preserve_default=False,
        ),
    ]
