# Generated by Django 5.0.3 on 2024-03-26 17:37

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_bank', '0004_product_cred_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='end_date',
            field=models.DateField(blank=True, validators=[django.core.validators.MinValueValidator(datetime.date(2024, 3, 26))], verbose_name='end_date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='start_date',
            field=models.DateField(blank=True, validators=[django.core.validators.MaxValueValidator(datetime.date(2024, 3, 26))], verbose_name='start_date'),
        ),
    ]
