# Generated by Django 5.0.3 on 2024-03-26 17:37

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_bank', '0005_alter_product_end_date_alter_product_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='start_date',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2024, 3, 26))], verbose_name='start_date'),
        ),
    ]
