# Generated by Django 5.0.3 on 2024-03-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_bank', '0007_alter_product_description_alter_product_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birthdate',
            field=models.DateField(verbose_name='birthdate'),
        ),
    ]
