# Generated by Django 5.0.3 on 2024-03-26 17:47

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_bank', '0008_alter_client_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birthdate',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2010, 3, 30))], verbose_name='birthdate'),
        ),
    ]
