# Generated by Django 5.0.3 on 2024-03-28 16:13

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_bank', '0009_alter_client_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Product image'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Product image'),
        ),
        migrations.AlterField(
            model_name='client',
            name='birthdate',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2010, 4, 1))], verbose_name='birthdate'),
        ),
        migrations.AlterField(
            model_name='product',
            name='end_date',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(2024, 3, 28))], verbose_name='end_date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='start_date',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(datetime.date(2024, 3, 28))], verbose_name='start_date'),
        ),
    ]
